package clientGUI;


import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import de.schlichtherle.io.FileReader;
import de.schlichtherle.io.FileWriter;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import smc.Concept;
import smc.Document;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author COMPAQ
 */
public class MapAdjust extends javax.swing.JFrame {

    /**
     * Creates new form MapAdjust
     */
    //tt
    List paths;
    String absolutePath;
    Document newDoc;
    ArrayList<Document> documents;
    public MapAdjust() {
        initComponents();
         paths=new ArrayList();
         documents=new ArrayList<Document>();
         jButton7.setEnabled(false);
         jButton6.setEnabled(false);
         jSlider1.setEnabled(false);
         jButton4.setEnabled(false);
         try {
                    String temp=new File("oo").getCanonicalPath();
                    int a=temp.lastIndexOf("\\");
                    absolutePath=temp.substring(0,a);
                    
                } catch (IOException ex) {
                    Logger.getLogger(MapAdjust.class.getName()).log(Level.SEVERE, null, ex);
                }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        panel1 = new java.awt.Panel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adjust Frame");

        jLabel1.setText("File Location");

        jLabel2.setText("Map View");

        jButton4.setText("Delete Relationship");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        jButton5.setText("Close");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Save Changes");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Upload the Document");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Browse Map");

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jButton1.setText("Adjust Map");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addGap(0, 879, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addGap(26, 26, 26)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addGap(13, 13, 13)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged

       
       
       
        
    }//GEN-LAST:event_jList1ValueChanged

    public void mapReload(Document doc){
    String actualpath=(String) paths.get(jList1.getSelectedIndex());
      // Document doc = documents.get(jList1.getSelectedIndex());
       JSCreator jsc = new JSCreator();

        try {
           jsc.CreateJS(doc,actualpath);


        } catch (IOException ex) {
            Logger.getLogger(MapAdjust.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        NativeInterface.open();
        panel1.removeAll();
          SwingUtilities.invokeLater(new Runnable() {
      public void run() {
                

          Web a=new Web(absolutePath+"\\visual\\example2.html");
          JScrollPane scrollPane = new JScrollPane(a);
          a.setBounds(0, 0, 700, 530);
          a.setVisible(true);
          
        panel1.add(a);
          
       
      }
    });
    }
    
    
    
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        try {
             //TODO add your handling code here:
           jButton7.setEnabled(true);
           jButton6.setEnabled(true);
           jSlider1.setEnabled(true);
           jButton4.setEnabled(true);
           FileWriter f1 = new FileWriter(absolutePath+"\\visual\\rnodes.dpi");
           f1.write("");
           f1.close();
         } catch (IOException ex) {
            Logger.getLogger(MapAdjust.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(jList1.getSelectedIndex()); 
        System.out.println("You have selected "+paths.get(jList1.getSelectedIndex()));
    //   System.out.println("You have selected file URI"+documents.get(jList1.getSelectedIndex()).getUri());
        String actualpath=(String) paths.get(jList1.getSelectedIndex());
        Document doc = documents.get(jList1.getSelectedIndex());
        DocumentFilter docFilter=new DocumentFilter();
        newDoc=docFilter.filterDocument(doc, 20,0.0f);
        JSCreator jsc = new JSCreator();

        try {
           jsc.CreateJS(newDoc,actualpath);


        } catch (IOException ex) {
            Logger.getLogger(MapAdjust.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        NativeInterface.open();
        panel1.removeAll();
          SwingUtilities.invokeLater(new Runnable() {
      public void run() {
                

          Web a=new Web(absolutePath+"\\visual\\example2.html");
          JScrollPane scrollPane = new JScrollPane(a);
          a.setBounds(0, 0, 700, 530);
          a.setVisible(true);
          
        panel1.add(a);
          
       
      }
    });
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        FileReader fr = null;
        ArrayList<String> deletedConcepts=new ArrayList<String>();
        
        try {
            fr = new FileReader(absolutePath+"\\visual\\rnodes.dpi");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MapAdjust.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader in = new BufferedReader(fr);
        String line;
        try {
            while ((line = in.readLine()) != null)
              deletedConcepts.add(line);
        } catch (IOException ex) {
            Logger.getLogger(MapAdjust.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        System.out.println("Deleted concpets ="+deletedConcepts);
        Document doc = documents.get(jList1.getSelectedIndex());
        for(String con:deletedConcepts){
            doc.deleteConcept(con);
            newDoc.deleteConcept(con);
        }
        System.out.println("deleted");
       // doc.printDoc();
        mapReload(newDoc);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
       // Document doc = documents.get(jList1.getSelectedIndex());
        DocumentUploader docloader=new DocumentUploader(newDoc);
        docloader.start();
        System.out.println(newDoc.getName()+ " is selected" ); 
       
    }//GEN-LAST:event_jButton7ActionPerformed

    int sliderValue=20;
    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
       // System.out.println(jSlider1.getValue());
        sliderValue=jSlider1.getValue();
       
        
    }//GEN-LAST:event_jSlider1StateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        deleteRelation deleteRel=new deleteRelation();
        deleteRel.setVisible(true);
        deleteRel.setLocationRelativeTo(null);
        Document doc = documents.get(jList1.getSelectedIndex());
        HashMap<String, Concept> mp = newDoc.getDoc();
      //  System.out.println(doc1.keySet());
        deleteRel.setNodeData(mp,doc,this,newDoc);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Document doc = documents.get(jList1.getSelectedIndex());
        DocumentFilter docFilter=new DocumentFilter();
        newDoc=docFilter.filterDocument(doc, sliderValue,0.5f);
        mapReload(newDoc);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void showLocation(String file){
        
        paths.add(file);
        
        
    }
    
    
    public void setDocumentsObjects(Document doc){
        documents.add(doc);
    }
    
    public ArrayList<Document> getDocumentObject(){
        return documents;
    }
    
    public void showPaths() throws IOException{
        System.out.println(paths);
       
        jList1.setListData(paths.toArray());
        
  
        
         // UIUtils.setPreferredLookAndFeel();
          NativeInterface.open();
          SwingUtilities.invokeLater(new Runnable() {
          public void run() {
      
            Web a=new Web(absolutePath+"\\visual\\html\\First.html");
            JScrollPane scrollPane = new JScrollPane(a);
            a.setBounds(0, 0, 700, 530);
            a.setVisible(true);
          
        panel1.add(a);
          
       
      }
    });
//    NativeInterface.runEventPump();
    }

       
    
    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
